export const FETCH_USER = 'FETCH_USER';

export const ITEMS_START = "ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_FAIL = "CREATE_ITEM_FAIL";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";

export const TOGGLE_FORM_DISPLAY_SUCCESS = "TOGGLE_FORM_DISPLAY_SUCCESS";
export const TOGGLE_FORM_DISPLAY_FAIL = "TOGGLE_FORM_DISPLAY_FAIL";

export const PANTRY_START = 'PANTRY_START';
export const ADD_TO_PANTRY_SUCCESS = 'ADD_TO_PANTRY_SUCCESS';
export const ADD_TO_PANTRY_FAIL = 'ADD_TO_PANTRY_FAIL';
export const REMOVE_FROM_PANTRY_SUCCESS = 'REMOVE_FROM_PANTRY_SUCCESS';
export const REMOVE_FROM_PANTRY_FAIL = 'REMOVE_FROM_PANTRY_FAIL';
export const GET_PANTRY_SUCCESS = 'GET_PANTRY_SUCCESS';
export const GET_PANTRY_FAIL = 'GET_PANTRY_FAIL';
export const CREATE_PANTRY_SUCCESS = 'CREATE_PANTRY_SUCCESS';
export const CREATE_PANTRY_FAIL = 'CREATE_PANTRY_FAIL';